[package]
name = "vieta-syntax"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
description = "Lossless concrete syntax and surface syntax for Vieta."

[lints]
workspace = true

[dependencies]
